export const atlasEndpoints = {
  projects: '/api/projects',
  project: (id: string) => `/api/projects/${id}`,
  projectAssets: (id: string) => `/api/projects/${id}/assets`,
  assets: '/api/assets',
  asset: (id: string) => `/api/assets/${id}`,
  assetImport: '/api/assets/import',
  runs: '/api/runs',
  activities: '/api/activities',
  notifications: '/api/notifications',
  capabilities: '/api/capabilities',
  studios: '/api/studios',
  commands: '/api/commands',
  workflows: '/api/workflows',
  workflow: (id: string) => `/api/workflow/${id}`,
  workflowExecute: (id: string) => `/api/workflow/${id}/execute`,
  execution: (id: string) => `/api/execution/${id}`,
  executionTimeline: (id: string) => `/api/execution/${id}/timeline`,
  search: '/api/search',
  executeWorkflow: '/api/workflows/execute',
  chatConversations: '/api/chat/conversations',
  chatConversation: (id: string) => `/api/chat/conversation/${id}`,
  chatMessage: '/api/chat/message',
  researchSession: '/api/research/session',
  researchSessionById: (id: string) => `/api/research/session/${id}`,
  researchSearch: '/api/research/search',
  researchSummarize: '/api/research/summarize',
  researchReport: '/api/research/report',
  researchGraph: (projectId: string) => `/api/research/graph/${projectId}`,
  reviews: '/api/reviews',
  reviewApprove: (id: string) => `/api/reviews/${id}/approve`,
  reviewReject: (id: string) => `/api/reviews/${id}/reject`,
  reviewComment: (id: string) => `/api/reviews/${id}/comment`,
  reviewPublish: (id: string) => `/api/reviews/${id}/publish`,
  reviewHistory: (id: string) => `/api/reviews/${id}/history`,
  imagesGenerate: '/api/images/generate',
  images: '/api/images',
  image: (id: string) => `/api/images/${id}`,
  imageVariant: (id: string) => `/api/images/${id}/variant`,
  imageRegenerate: (id: string) => `/api/images/${id}/regenerate`,
  imageVersions: (id: string) => `/api/images/${id}/versions`,
  workspaceContext: (projectId: string) => `/api/workspace/context/${projectId}`,
  workspaceRecommendations: (projectId: string) => `/api/workspace/recommendations/${projectId}`,
  workspaceRecent: (projectId: string) => `/api/workspace/recent/${projectId}`,
  workspaceDashboard: (projectId: string) => `/api/workspace/dashboard/${projectId}`,
  agents: '/api/agents',
  agent: (id: string) => `/api/agents/${id}`,
  agentMemory: (id: string) => `/api/agents/${id}/memory`,
  agentPermissions: (id: string) => `/api/agents/${id}/permissions`,
  agentPlan: (id: string) => `/api/agents/${id}/plan`,
  schedulerSchedule: '/api/scheduler/schedule',
  schedulerById: (id: string) => `/api/scheduler/${id}`,
  schedulerQueue: (id: string) => `/api/scheduler/${id}/queue`,
  schedulerPause: (id: string) => `/api/scheduler/${id}/pause`,
  schedulerResume: (id: string) => `/api/scheduler/${id}/resume`,
  schedulerCancel: (id: string) => `/api/scheduler/${id}/cancel`,
  runtimeStartSchedule: (id: string) => `/api/runtime/schedule/${id}/start`,
  runtime: '/api/runtime',
  runtimeRunning: '/api/runtime/running',
  runtimeHistory: '/api/runtime/history',
  runtimeById: (id: string) => `/api/runtime/${id}`,
  runtimeCancel: (id: string) => `/api/runtime/${id}/cancel`,
  runtimeRetry: (id: string) => `/api/runtime/${id}/retry`,
  agentTeam: '/api/agents/team',
  agentTeamById: (id: string) => `/api/agents/team/${id}`,
  agentTeamMessages: (id: string) => `/api/agents/team/${id}/messages`,
  agentTeamCancel: (id: string) => `/api/agents/team/${id}/cancel`,
  agentTeamStatus: (id: string) => `/api/agents/team/${id}/status`,
  graphProject: (id: string) => `/api/graph/project/${id}`,
  graphNode: (id: string) => `/api/graph/node/${id}`,
  graphNeighbors: (id: string) => `/api/graph/node/${id}/neighbors`,
  graphPath: '/api/graph/path',
  graphContext: (id: string) => `/api/graph/context/${id}`,
  graphLineage: (id: string) => `/api/graph/lineage/${id}`,
  graphHistory: (id: string) => `/api/graph/history/${id}`,
  automation: '/api/automation',
  automationById: (id: string) => `/api/automation/${id}`,
  automationEnable: (id: string) => `/api/automation/${id}/enable`,
  automationDisable: (id: string) => `/api/automation/${id}/disable`,
  automationRun: (id: string) => `/api/automation/${id}/run`,
  automationDryRun: (id: string) => `/api/automation/${id}/dry-run`,
  automationHistory: (id: string) => `/api/automation/${id}/history`,
  automationState: (id: string) => `/api/automation/${id}/state`,
  automationRuns: '/api/automation/runs',
  automationLogs: '/api/automation/logs',
  automationConflicts: '/api/automation/conflicts',
  approvals: '/api/approvals',
  approvalById: (id: string) => `/api/approvals/${id}`,
  approvalApprove: (id: string) => `/api/approvals/${id}/approve`,
  approvalReject: (id: string) => `/api/approvals/${id}/reject`,
  approvalRequestChanges: (id: string) => `/api/approvals/${id}/request-changes`,
  approvalCancel: (id: string) => `/api/approvals/${id}/cancel`,
  approvalView: (id: string) => `/api/approvals/${id}/view`,
  approvalEscalate: (id: string) => `/api/approvals/${id}/escalate`,
  approvalResumeExecution: (id: string) => `/api/approvals/${id}/resume-execution`,
  approvalHistory: '/api/approvals/history',
  approvalWaitingExecutions: '/api/approvals/waiting-executions',
  approvalPolicies: '/api/approval-policies',
  workers: '/api/workers',
  workerRegister: '/api/workers/register',
  workerHeartbeat: '/api/workers/heartbeat',
  workerById: (id: string) => `/api/workers/${id}`,
  workerPause: (id: string) => `/api/workers/${id}/pause`,
  workerResume: (id: string) => `/api/workers/${id}/resume`,
  workerDrain: (id: string) => `/api/workers/${id}/drain`,
  cluster: '/api/cluster',
  clusterHealth: '/api/cluster/health',
  clusterLoad: '/api/cluster/load',
  clusterReservations: '/api/cluster/reservations',
  clusterLeases: '/api/cluster/leases',
  clusterWaitingPlacement: '/api/cluster/waiting-placement',
  clusterSweep: '/api/cluster/sweep',
  clusterRecover: (id: string) => `/api/cluster/executions/${id}/recover`,
  clusterRetryPlacement: (id: string) => `/api/cluster/executions/${id}/retry-placement`,
  organizations: '/api/organizations',
  organizationById: (id: string) => `/api/organizations/${id}`,
  organizationMembers: (id: string) => `/api/organizations/${id}/members`,
  organizationMember: (orgId: string, membershipId: string) =>
    `/api/organizations/${orgId}/members/${membershipId}`,
  organizationPermissions: (orgId: string, identityId: string) =>
    `/api/organizations/${orgId}/permissions/${identityId}`,
  organizationWorker: (orgId: string, workerId: string) =>
    `/api/organizations/${orgId}/workers/${workerId}`,
  orgRoles: '/api/roles',
  orgRoleById: (id: string) => `/api/roles/${id}`,
  orgPermissions: '/api/permissions',
  orgTeams: '/api/teams',
  policies: '/api/policies',
  policiesResolve: '/api/policies/resolve',
  audit: '/api/audit',
  auditById: (id: string) => `/api/audit/${id}`,
  identities: '/api/identities',
  identityProviders: '/api/identity-providers',
} as const
